name: weather_app
description: flutter project for check weather

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  rest_client: ^2.1.4+7
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  path_provider: ^2.0.11
  cupertino_icons: ^1.0.2
  flutter_logs: ^2.1.7
  json_annotation: 4.6.0
  sqflite: ^2.0.3+1
  intl: ^0.17.0


dev_dependencies:
  build_runner: ^2.2.0
  json_serializable: ^6.3.1

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

flutter_intl:
  enabled: true
